package io.github.sceneview.ar.rerun

import android.util.Log
import com.google.ar.core.Anchor
import com.google.ar.core.Frame
import com.google.ar.core.HitResult
import com.google.ar.core.Plane
import com.google.ar.core.Pose
import com.google.ar.core.Session
import com.google.ar.core.TrackingState
import io.github.sceneview.ar.arcore.getUpdatedPlanes
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.launch
import java.io.BufferedWriter
import java.io.OutputStreamWriter
import java.net.InetSocketAddress
import java.net.Socket

/**
 * Streams ARCore session data to a Rerun viewer over TCP using the
 * JSON-lines wire format defined by [RerunWireFormat].
 *
 * ### Why this exists
 *
 * Rerun has no native Kotlin SDK. The bridge emits one JSON object per line
 * and a tiny Python sidecar (`tools/rerun-bridge.py`, generated by the
 * `rerun-3d-mcp` package) reads the socket and re-logs each event into the
 * Rerun viewer as the matching archetype (`Transform3D`, `Points3D`,
 * `LineStrips3D`, …). The developer runs the sidecar + `rerun` on their
 * dev machine, then `adb reverse tcp:9876 tcp:9876` and launches the app.
 *
 * ### Threading
 *
 * All I/O runs on [Dispatchers.IO] via a dedicated supervisor scope. The
 * public `log*` methods are non-blocking: each event is enqueued on a
 * rendezvous [Channel] with `CONFLATED` behaviour so the newest event wins
 * and backpressure drops frames silently. This is the only correct choice
 * for a render-loop callback — Filament's main-thread contract forbids
 * blocking inside `onSessionUpdated`.
 *
 * ### Usage
 *
 * Prefer the composable [rememberRerunBridge] helper; this class is public
 * so non-Compose hosts (plain `View`s, unit tests) can still use it.
 *
 * ```kotlin
 * val bridge = RerunBridge(host = "127.0.0.1", port = 9876, rateHz = 10)
 * bridge.connect()
 * try {
 *     arSession.onFrame { frame -> bridge.logFrame(session, frame) }
 * } finally {
 *     bridge.disconnect()
 * }
 * ```
 *
 * @param host Host to connect to. Use `127.0.0.1` with `adb reverse tcp:$port tcp:$port`.
 * @param port TCP port the Python sidecar listens on.
 * @param rateHz Maximum number of frames logged per second. Later events are dropped.
 *               Default: 10 Hz. Set to `0` to disable throttling.
 * @param tag Logcat tag used for connection errors.
 */
public class RerunBridge
@JvmOverloads
public constructor(
    private val host: String = DEFAULT_HOST,
    private val port: Int = DEFAULT_PORT,
    private val rateHz: Int = DEFAULT_RATE_HZ,
    private val tag: String = "RerunBridge",
) {

    public companion object {
        public const val DEFAULT_HOST: String = "127.0.0.1"
        public const val DEFAULT_PORT: Int = 9876
        public const val DEFAULT_RATE_HZ: Int = 10
    }

    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    // Conflated channel: the sender never blocks; a new event replaces any
    // pending one. This gives us drop-on-backpressure semantics for free.
    private val outbox = Channel<String>(capacity = Channel.CONFLATED)

    @Volatile private var socket: Socket? = null
    @Volatile private var writer: BufferedWriter? = null
    @Volatile private var writerJob: Job? = null
    @Volatile private var lastEmitNanos: Long = 0L

    // Runtime kill-switch. When `false`, every `log*` call is a no-op and we
    // don't even build the JSON string — safe to wire unconditionally in
    // release builds and gate with `BuildConfig.DEBUG`.
    @Volatile private var enabled: Boolean = true

    private val minIntervalNanos: Long =
        if (rateHz <= 0) 0L else (1_000_000_000L / rateHz)

    /**
     * Open the TCP socket on a background thread and start the writer loop.
     * Safe to call multiple times: no-op if already connected.
     */
    public fun connect() {
        if (writerJob?.isActive == true) return
        writerJob = scope.launch {
            try {
                val s = Socket()
                s.connect(InetSocketAddress(host, port), /* timeout = */ 2000)
                val w = BufferedWriter(OutputStreamWriter(s.getOutputStream(), Charsets.UTF_8))
                socket = s
                writer = w
                for (line in outbox) {
                    try {
                        w.write(line)
                        w.flush()
                    } catch (e: Exception) {
                        Log.w(tag, "write failed: ${e.message}")
                        break
                    }
                }
            } catch (e: Exception) {
                Log.w(tag, "connect to $host:$port failed: ${e.message}")
            } finally {
                closeQuietly()
            }
        }
    }

    /**
     * Stop the writer loop and close the socket. Safe to call multiple times.
     * The bridge can be reused: call [connect] again to re-open.
     */
    public fun disconnect() {
        writerJob?.cancel()
        writerJob = null
        closeQuietly()
    }

    /** Release all resources. The bridge is unusable after this call. */
    public fun close() {
        disconnect()
        scope.cancel()
        outbox.close()
    }

    /**
     * Toggle the bridge at runtime. When `false`, every `log*` call is a
     * no-op and no JSON is built. Calling [connect]/[disconnect] is still
     * the right way to manage the socket — this only guards the hot path.
     */
    public fun setEnabled(enabled: Boolean) {
        this.enabled = enabled
    }

    // ── High-level convenience ────────────────────────────────────────────

    /**
     * Log everything useful about a single ARCore frame — camera pose,
     * currently tracked planes, and the point cloud. Honours the rate
     * limiter: the whole frame is either logged or dropped as one unit,
     * so you can't log half a frame.
     */
    public fun logFrame(session: Session, frame: Frame) {
        if (!enabled) return
        if (!shouldEmit(frame.timestamp)) return
        logCameraPose(frame.camera.pose, frame.timestamp)
        for (plane in frame.getUpdatedPlanes()) {
            if (plane.trackingState != TrackingState.TRACKING) continue
            enqueue(RerunWireFormat.plane(frame.timestamp, plane))
        }
        try {
            frame.acquirePointCloud().use { cloud ->
                enqueue(RerunWireFormat.pointCloud(frame.timestamp, cloud))
            }
        } catch (e: Exception) {
            // Point cloud acquisition can fail if the depth API isn't ready
            // — not a hard error, just drop the event for this frame.
            Log.v(tag, "pointCloud skipped: ${e.message}")
        }
    }

    // ── Low-level per-event loggers ───────────────────────────────────────

    public fun logCameraPose(pose: Pose, timestampNanos: Long) {
        if (!enabled) return
        enqueue(RerunWireFormat.cameraPose(timestampNanos, pose))
    }

    public fun logPlanes(planes: Collection<Plane>, timestampNanos: Long) {
        if (!enabled) return
        for (plane in planes) {
            if (plane.trackingState != TrackingState.TRACKING) continue
            enqueue(RerunWireFormat.plane(timestampNanos, plane))
        }
    }

    public fun logPointCloud(cloud: com.google.ar.core.PointCloud, timestampNanos: Long) {
        if (!enabled) return
        enqueue(RerunWireFormat.pointCloud(timestampNanos, cloud))
    }

    public fun logAnchors(anchors: Collection<Anchor>, timestampNanos: Long) {
        if (!enabled) return
        for (anchor in anchors) enqueue(RerunWireFormat.anchor(timestampNanos, anchor))
    }

    public fun logHitResult(hit: HitResult, timestampNanos: Long) {
        if (!enabled) return
        enqueue(RerunWireFormat.hitResult(timestampNanos, hit))
    }

    // ── Internals ─────────────────────────────────────────────────────────

    /**
     * Returns true if an event at the given device timestamp should be
     * emitted under the configured rate limiter. Must run on whatever
     * thread the caller is on — this is a hot-path check on the render
     * thread, so we use a volatile long and no locking.
     */
    private fun shouldEmit(timestampNanos: Long): Boolean {
        if (minIntervalNanos <= 0L) return true
        val delta = timestampNanos - lastEmitNanos
        if (delta < minIntervalNanos) return false
        lastEmitNanos = timestampNanos
        return true
    }

    /**
     * Enqueue a serialized JSON line for the writer loop. Non-blocking —
     * uses `trySend`, so if the channel already has a pending event the
     * new one overwrites it (conflated).
     */
    private fun enqueue(line: String) {
        outbox.trySend(line)
    }

    private fun closeQuietly() {
        try { writer?.close() } catch (_: Exception) {}
        try { socket?.close() } catch (_: Exception) {}
        writer = null
        socket = null
    }

    /**
     * Internal hook for unit tests: enqueue a pre-built JSON line directly,
     * bypassing the `enabled` flag and the rate limiter. Lets the socket
     * tests exercise the writer loop without needing a real ARCore [Pose].
     *
     * Do NOT call from production code — use the public `log*` methods.
     */
    internal fun testOnlyEnqueue(line: String) {
        outbox.trySend(line)
    }
}
