#if os(iOS)
import Foundation
import Network
import ARKit

/// Streams ARKit session data to a Rerun viewer over TCP using the
/// JSON-lines wire format defined by ``RerunWireFormat``.
///
/// ### Why this exists
///
/// Rerun has no native Swift SDK. The bridge emits one JSON object per line
/// and a tiny Python sidecar (`tools/rerun-bridge.py`, generated by the
/// `rerun-3d-mcp` package) reads the socket and re-logs each event into the
/// Rerun viewer as the matching archetype (`Transform3D`, `Points3D`,
/// `LineStrips3D`, …). The developer runs the sidecar + `rerun` on their
/// Mac, connects the iPhone via USB (or same LAN), and launches the app.
///
/// ### Threading
///
/// All I/O runs on a dedicated background [`DispatchQueue`] via `NWConnection`
/// — Apple's recommended API for TCP clients on iOS. The public `log*`
/// methods are non-blocking: each event is serialized on the caller's
/// thread (typically the ARKit delegate queue) and handed to `NWConnection`,
/// which buffers it internally. There's no in-process queue; backpressure
/// is absorbed by ``rateHz``.
///
/// ### Usage
///
/// ```swift
/// @StateObject private var bridge = RerunBridge(host: "127.0.0.1", port: 9876, rateHz: 10)
///
/// var body: some View {
///     ARSceneView()
///         .onFrame { frame, _ in
///             bridge.logFrame(frame)
///         }
///         .onAppear { bridge.connect() }
///         .onDisappear { bridge.disconnect() }
/// }
/// ```
///
/// - Parameters:
///   - host: Host to connect to. Use the Mac's LAN IP, or `127.0.0.1` if
///     tethering over USB with a port forwarder.
///   - port: TCP port the Python sidecar listens on.
///   - rateHz: Maximum frames logged per second. Later events are dropped.
///     Default `10`. Set to `0` to disable throttling.
public final class RerunBridge: ObservableObject {

    public static let defaultHost: String = "127.0.0.1"
    public static let defaultPort: UInt16 = 9876
    public static let defaultRateHz: Int = 10

    private let host: String
    private let port: UInt16
    private let rateHz: Int

    /// NWConnection runs its own queue internally, but every `send` must be
    /// called from a consistent queue — we use this private one.
    private let queue = DispatchQueue(label: "io.github.sceneview.rerun-bridge", qos: .utility)

    private var connection: NWConnection?
    private var lastEmitNanos: Int64 = 0
    private var _enabled: Bool = true
    private let minIntervalNanos: Int64

    /// Total number of events successfully enqueued this session. Published
    /// so a SwiftUI view can bind an overlay to it.
    @Published public private(set) var eventCount: Int = 0

    public init(
        host: String = RerunBridge.defaultHost,
        port: UInt16 = RerunBridge.defaultPort,
        rateHz: Int = RerunBridge.defaultRateHz
    ) {
        self.host = host
        self.port = port
        self.rateHz = rateHz
        self.minIntervalNanos = rateHz <= 0 ? 0 : Int64(1_000_000_000 / rateHz)
    }

    // MARK: - Connection lifecycle

    /// Open the TCP connection on a background queue. Safe to call multiple
    /// times: no-op if already connecting or ready.
    public func connect() {
        queue.async { [weak self] in
            guard let self = self else { return }
            if let existing = self.connection,
               existing.state == .ready || existing.state == .preparing {
                return
            }
            guard let nwPort = NWEndpoint.Port(rawValue: self.port) else { return }
            let nwHost = NWEndpoint.Host(self.host)
            let conn = NWConnection(host: nwHost, port: nwPort, using: .tcp)
            conn.stateUpdateHandler = { state in
                switch state {
                case .failed(let err):
                    NSLog("[RerunBridge] failed: \(err.localizedDescription)")
                case .cancelled:
                    NSLog("[RerunBridge] cancelled")
                default:
                    break
                }
            }
            conn.start(queue: self.queue)
            self.connection = conn
        }
    }

    /// Cancel the connection. Safe to call multiple times.
    public func disconnect() {
        queue.async { [weak self] in
            self?.connection?.cancel()
            self?.connection = nil
        }
    }

    /// Toggle the bridge at runtime. When `false`, every `log*` call is a
    /// no-op and no JSON is built.
    public func setEnabled(_ enabled: Bool) {
        queue.async { [weak self] in
            self?._enabled = enabled
        }
    }

    // MARK: - High-level convenience

    /// Log everything useful about a single ARKit frame — camera pose,
    /// currently tracked plane anchors, and the raw feature cloud.
    /// Honours the rate limiter.
    public func logFrame(_ frame: ARFrame) {
        guard _enabled else { return }
        let tNanos = Int64(frame.timestamp * 1_000_000_000)
        guard shouldEmit(tNanos) else { return }
        send(RerunWireFormat.cameraPose(timestampNanos: tNanos, camera: frame.camera))
        for anchor in frame.anchors {
            if let plane = anchor as? ARPlaneAnchor {
                send(RerunWireFormat.plane(timestampNanos: tNanos, anchor: plane))
            }
        }
        if let cloud = frame.rawFeaturePoints {
            send(RerunWireFormat.pointCloud(timestampNanos: tNanos, cloud: cloud))
        }
    }

    // MARK: - Low-level per-event loggers

    public func logCameraPose(_ camera: ARCamera, timestampNanos: Int64) {
        guard _enabled else { return }
        send(RerunWireFormat.cameraPose(timestampNanos: timestampNanos, camera: camera))
    }

    public func logPlanes(_ planes: [ARPlaneAnchor], timestampNanos: Int64) {
        guard _enabled else { return }
        for anchor in planes {
            send(RerunWireFormat.plane(timestampNanos: timestampNanos, anchor: anchor))
        }
    }

    public func logPointCloud(_ cloud: ARPointCloud, timestampNanos: Int64) {
        guard _enabled else { return }
        send(RerunWireFormat.pointCloud(timestampNanos: timestampNanos, cloud: cloud))
    }

    public func logAnchors(_ anchors: [ARAnchor], timestampNanos: Int64) {
        guard _enabled else { return }
        for anchor in anchors {
            send(RerunWireFormat.anchor(timestampNanos: timestampNanos, arAnchor: anchor))
        }
    }

    // MARK: - Internals

    /// Returns true if an event at the given timestamp should be emitted
    /// under the configured rate limiter.
    private func shouldEmit(_ timestampNanos: Int64) -> Bool {
        if minIntervalNanos <= 0 { return true }
        let delta = timestampNanos - lastEmitNanos
        if delta < minIntervalNanos { return false }
        lastEmitNanos = timestampNanos
        return true
    }

    /// Send a serialized JSON line to the connection. Scheduled on the
    /// bridge's private queue so we never hit NWConnection from two threads.
    private func send(_ line: String) {
        queue.async { [weak self] in
            guard let self = self, let conn = self.connection else { return }
            guard conn.state == .ready || conn.state == .preparing else { return }
            let data = Data(line.utf8)
            conn.send(
                content: data,
                completion: .contentProcessed { [weak self] error in
                    if let error = error {
                        NSLog("[RerunBridge] send failed: \(error.localizedDescription)")
                        return
                    }
                    DispatchQueue.main.async {
                        self?.eventCount += 1
                    }
                }
            )
        }
    }

    /// Internal hook for unit tests — enqueue a pre-built JSON line
    /// directly so the tests don't need a real ARFrame.
    internal func testOnlyEnqueue(_ line: String) {
        send(line)
    }
}
#endif
