#if os(iOS) || os(macOS) || os(visionOS)
import XCTest
import RealityKit
@testable import SceneViewSwift

final class PhysicsNodeTests: XCTestCase {

    func testDynamic() {
        let cube = GeometryNode.cube(size: 0.5, color: .red)
        let physics = PhysicsNode.dynamic(cube.entity, mass: 2.0)
        XCTAssertEqual(physics.mode, .dynamic)
        XCTAssertNotNil(cube.entity.components[PhysicsBodyComponent.self])
        XCTAssertNotNil(cube.entity.components[PhysicsMotionComponent.self])
    }

    func testStatic() {
        let plane = GeometryNode.plane(width: 10, depth: 10, color: .gray)
        let physics = PhysicsNode.static(plane.entity)
        XCTAssertEqual(physics.mode, .static)
        XCTAssertNotNil(plane.entity.components[PhysicsBodyComponent.self])
        // Static bodies should not have motion component
        XCTAssertNil(plane.entity.components[PhysicsMotionComponent.self])
    }

    func testKinematic() {
        let sphere = GeometryNode.sphere(radius: 0.3, color: .blue)
        let physics = PhysicsNode.kinematic(sphere.entity)
        XCTAssertEqual(physics.mode, .kinematic)
        XCTAssertNotNil(sphere.entity.components[PhysicsBodyComponent.self])
        XCTAssertNotNil(sphere.entity.components[PhysicsMotionComponent.self])
    }

    func testPhysicsMaterial() {
        let cube = GeometryNode.cube(size: 0.5, color: .white)
        _ = PhysicsNode.dynamic(
            cube.entity,
            mass: 1.0,
            restitution: 0.8,
            friction: 0.3
        )
        // Just verify it doesn't crash — material properties are internal to RealityKit
        XCTAssertNotNil(cube.entity.components[PhysicsBodyComponent.self])
    }

    func testCollisionAutoGenerated() {
        let cube = GeometryNode.cube(size: 0.5, color: .green)
        // Remove collision first to test auto-generation
        cube.entity.components.remove(CollisionComponent.self)
        _ = PhysicsNode.dynamic(cube.entity)
        // Physics application should auto-generate collision if missing
        XCTAssertNotNil(cube.entity.components[CollisionComponent.self])
    }

    func testSetVelocity() {
        let cube = GeometryNode.cube(size: 0.5, color: .red)
        _ = PhysicsNode.dynamic(cube.entity)
        PhysicsNode.setVelocity(cube.entity, velocity: .init(x: 0, y: 5, z: 0))
        if let motion = cube.entity.components[PhysicsMotionComponent.self] {
            XCTAssertEqual(motion.linearVelocity.y, 5.0, accuracy: 0.001)
        }
    }

    func testSetAngularVelocity() {
        let cube = GeometryNode.cube(size: 0.5, color: .red)
        _ = PhysicsNode.dynamic(cube.entity)
        PhysicsNode.setAngularVelocity(cube.entity, angularVelocity: .init(x: 0, y: 1, z: 0))
        if let motion = cube.entity.components[PhysicsMotionComponent.self] {
            XCTAssertEqual(motion.angularVelocity.y, 1.0, accuracy: 0.001)
        }
    }

    // MARK: - Apply impulse

    func testApplyImpulseOnDynamicBody() {
        let cube = GeometryNode.cube(size: 0.5, color: .red)
        _ = PhysicsNode.dynamic(cube.entity)
        // Should not crash
        PhysicsNode.applyImpulse(to: cube.entity, impulse: .init(x: 0, y: 10, z: 0))
        XCTAssertNotNil(cube.entity.components[PhysicsBodyComponent.self])
    }

    func testApplyImpulseOnNonModelEntityNoOp() {
        let entity = Entity()
        // Non-ModelEntity should be a no-op (guard clause)
        PhysicsNode.applyImpulse(to: entity, impulse: .init(x: 0, y: 10, z: 0))
        XCTAssertNotNil(entity)
    }

    // MARK: - Velocity on entity without motion component

    func testSetVelocityOnEntityWithoutMotionComponentNoOp() {
        let entity = Entity()
        // No motion component: should be a no-op
        PhysicsNode.setVelocity(entity, velocity: .init(x: 1, y: 0, z: 0))
        XCTAssertNil(entity.components[PhysicsMotionComponent.self])
    }

    func testSetAngularVelocityOnEntityWithoutMotionComponentNoOp() {
        let entity = Entity()
        PhysicsNode.setAngularVelocity(entity, angularVelocity: .init(x: 0, y: 1, z: 0))
        XCTAssertNil(entity.components[PhysicsMotionComponent.self])
    }

    // MARK: - Mode enum

    func testModeEnumValues() {
        let modes: [PhysicsNode.Mode] = [.dynamic, .static, .kinematic]
        XCTAssertEqual(modes.count, 3)
    }

    // MARK: - Physics entity reference

    func testDynamicReturnsCorrectEntity() {
        let cube = GeometryNode.cube(size: 0.5)
        let physics = PhysicsNode.dynamic(cube.entity)
        XCTAssertTrue(physics.entity === cube.entity)
    }

    func testStaticReturnsCorrectEntity() {
        let plane = GeometryNode.plane()
        let physics = PhysicsNode.static(plane.entity)
        XCTAssertTrue(physics.entity === plane.entity)
    }

    func testKinematicReturnsCorrectEntity() {
        let sphere = GeometryNode.sphere()
        let physics = PhysicsNode.kinematic(sphere.entity)
        XCTAssertTrue(physics.entity === sphere.entity)
    }

    // MARK: - Zero mass dynamic

    func testDynamicWithZeroMass() {
        let cube = GeometryNode.cube(size: 0.5)
        let physics = PhysicsNode.dynamic(cube.entity, mass: 0.0)
        XCTAssertEqual(physics.mode, .dynamic)
        XCTAssertNotNil(cube.entity.components[PhysicsBodyComponent.self])
    }

    // MARK: - Edge case restitution/friction

    func testDynamicWithZeroRestitutionAndFriction() {
        let cube = GeometryNode.cube(size: 0.5)
        let physics = PhysicsNode.dynamic(cube.entity, restitution: 0.0, friction: 0.0)
        XCTAssertEqual(physics.mode, .dynamic)
    }

    func testDynamicWithMaxRestitution() {
        let cube = GeometryNode.cube(size: 0.5)
        let physics = PhysicsNode.dynamic(cube.entity, restitution: 1.0, friction: 1.0)
        XCTAssertEqual(physics.mode, .dynamic)
    }
}
#endif
